kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2020-05-15T06:50:38Z
  name: build-config
  namespace: go-demo-3-build
data:
  build-config.properties: |
    project=go-demo-3
    image=trenunu/go-demo-3
    domain=acme.com
    addr=go-demo-3.acme.com
    cmAddr=cm.acme.com
    chartVer=0.0.1

